# Generated by Django 5.1 on 2026-02-06 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado Común',
                'verbose_name_plural': 'Estados Comunes',
                'db_table': 'tbl_common_status',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.commonstatus')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'tbl_users',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('patient_cip', models.CharField(blank=True, help_text='CIP del paciente', max_length=50, null=True)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10)),
                ('ticket_status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Proceso'), ('resolved', 'Resuelto'), ('closed', 'Cerrado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('message', models.TextField(help_text='Mensaje inicial de la notificación')),
                ('attachment', models.CharField(blank=True, help_text='Ruta de imagen adjunta', max_length=255, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Usuario asignado (médico o farmacéutico)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_notifications', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Usuario que crea la notificación (médico o farmacéutico)', on_delete=django.db.models.deletion.PROTECT, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='core.commonstatus')),
            ],
            options={
                'verbose_name': 'Notificación/Ticket',
                'verbose_name_plural': 'Notificaciones/Tickets',
                'db_table': 'tbl_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('attachment', models.CharField(blank=True, help_text='Ruta de archivo adjunto', max_length=255, null=True)),
                ('is_internal', models.BooleanField(default=False, help_text='Nota interna (solo visible para farmacia)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.notification')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_messages', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='notification_messages', to='core.commonstatus')),
            ],
            options={
                'verbose_name': 'Mensaje de Notificación',
                'verbose_name_plural': 'Mensajes de Notificaciones',
                'db_table': 'tbl_notification_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Nombre del ícono', max_length=50, null=True)),
                ('color', models.CharField(default='#6c757d', help_text='Color hex', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='notification_types', to='core.commonstatus')),
            ],
            options={
                'verbose_name': 'Tipo de Notificación',
                'verbose_name_plural': 'Tipos de Notificaciones',
                'db_table': 'tbl_notification_types',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='core.notificationtype'),
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Código único de la farmacia', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacies', to='core.commonstatus')),
            ],
            options={
                'verbose_name': 'Farmacia',
                'verbose_name_plural': 'Farmacias',
                'db_table': 'tbl_pharmacy',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='pharmacy',
            field=models.ForeignKey(help_text='Farmacia destinataria', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.pharmacy'),
        ),
        migrations.CreateModel(
            name='PharmacyData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='España', max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('license_number', models.CharField(help_text='Número de licencia', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='core.pharmacy')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_data', to='core.commonstatus')),
            ],
            options={
                'verbose_name': 'Datos de Farmacia',
                'verbose_name_plural': 'Datos de Farmacias',
                'db_table': 'tbl_pharmacy_data',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_data', to='core.commonstatus')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datos de Usuario',
                'verbose_name_plural': 'Datos de Usuarios',
                'db_table': 'tbl_user_data',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_roles', to='core.commonstatus')),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuario',
                'db_table': 'tbl_user_roles',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.userrole'),
        ),
        migrations.CreateModel(
            name='PharmacyUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_manager', models.BooleanField(default=False, help_text='Es responsable de la farmacia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_users', to='core.pharmacy')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_users', to='core.commonstatus')),
                ('user', models.ForeignKey(limit_choices_to={'role__name': 'Farmacéutico'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_pharmacies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmacéutico-Farmacia',
                'verbose_name_plural': 'Farmacéuticos-Farmacias',
                'db_table': 'tbl_pharmacy_users',
                'unique_together': {('pharmacy', 'user')},
            },
        ),
    ]
