# Generated by Django 5.1 on 2026-02-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacydata',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pharmacydata',
            name='logo',
            field=models.CharField(blank=True, help_text='URL del logo', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pharmacydata',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
