# Generated by Django 5.1 on 2026-02-07 05:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_pharmacy_geo_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_cip', models.CharField(help_text='CIP del paciente', max_length=50)),
                ('patient_name', models.CharField(blank=True, help_text='Nombre del paciente', max_length=255, null=True)),
                ('patient_birth_date', models.DateField(blank=True, help_text='Fecha de nacimiento', null=True)),
                ('medication', models.CharField(help_text='Medicamento recetado', max_length=255)),
                ('dosage', models.CharField(blank=True, help_text='Posología', max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Cantidad')),
                ('instructions', models.TextField(blank=True, help_text='Instrucciones de uso', null=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now, help_text='Fecha de emisión')),
                ('expiry_date', models.DateField(blank=True, help_text='Fecha de caducidad', null=True)),
                ('prescription_status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activa'), ('dispensed', 'Dispensada'), ('expired', 'Caducada'), ('cancelled', 'Cancelada')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales', null=True)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispensed_by', models.ForeignKey(blank=True, help_text='Farmacéutico que dispensó', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_dispensed', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(help_text='Médico que crea la receta', on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions_created', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(blank=True, help_text='Farmacia destinataria (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='core.pharmacy')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='core.commonstatus')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'db_table': 'tbl_prescriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
